name: genetrust
description: "A Flutter application for GeneTrust AI Studio"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  flutter_riverpod: ^2.4.0
  go_router: ^13.0.0
  flutter_svg: ^2.0.9
  shared_preferences: ^2.2.2
  fl_chart: ^0.65.0
  intl: ^0.19.0
  firebase_core: ^3.1.0
  firebase_auth: ^5.0.0
  firebase_database: ^11.3.2
  firebase_storage: ^12.4.2
  cloud_firestore: ^5.6.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/ 