name: genetrust
description: "A Flutter application for GeneTrust AI Studio"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  flutter_riverpod: ^2.4.0
  go_router: ^13.0.0
  flutter_svg: ^2.0.9
  shared_preferences: ^2.2.2
  fl_chart: ^0.65.0
  intl: ^0.20.2
  firebase_core: ^3.1.0
  firebase_auth: ^5.0.0
  firebase_database: ^11.3.2
  firebase_storage: ^12.4.2
  cloud_firestore: ^5.6.3
  google_generative_ai: ^0.1.0
  share_plus: ^11.0.0
  flutter_tts: ^4.2.3
  url_launcher: ^6.3.1
  flutter_animate: ^4.5.2
  image_picker: ^1.1.2
  universal_html: ^2.2.4
  flutter_markdown: ^0.7.7+1
  pdf: ^3.11.3
  path_provider: ^2.1.5
  open_file: ^3.5.10
  record: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/ 